Numpy Library

In [1]:
#import numpy library
import numpy as np

In [14]:
#create an array use this line of code
x=np.array([1,2,3])
x

array([1, 2, 3])

In [15]:
#to check dimension of array
x.ndim

1

In [16]:
#to check shape of an array
x.shape

(3,)

In [17]:
#to check size of an array
x.size

3

In [18]:
#to check the data type
x.dtype

dtype('int32')

In [22]:
#read the first element in the array
x[0]

1

In [23]:
# First 2 elements: 0 & 1 , until before 2
x[:2]

array([1, 2])

In [25]:
#Save the array:
np.save('data',x)

In [26]:
#load the array
np.load("data.npy")

array([1, 2, 3])

In [27]:
5*x

array([ 5, 10, 15])

EXCERCISE

In [28]:
Y=np.array([[1,2,3],[4,5,6]])
Y

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
Y.ndim

2

In [32]:
Y.shape

(2, 3)

In [57]:
Y[0:1,:2]

array([[1, 2]])